### ISSUE TITLE
PHP Fatal error in carousel: Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by mcguffin** [vanokhin/shortcodes-ultimate#108] opened 2020-04-06 11:07 UTC
**Describe the bug**
PHP throws a exception if a coarousel slide does not have an image.

The Shortcode:
```
[su_carousel source="category: 12" link="post" target="blank" width="200" height="100" responsive="no" items="1" centered="no" arrows="no" mousewheel="no" autoplay="50" speed="4000"]
```

PHP Error log:
```
[06-Apr-2020 10:43:16 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /<WEBROOT>/httpdocs/wp-content/plugins/shortcodes-ultimate/includes/shortcodes/carousel.php:201
Stack trace:
#0 /<WEBROOT>/httpdocs/wp-includes/shortcodes.php(343): su_shortcode_carousel(Array, '', 'su_carousel')
#1 [internal function]: do_shortcode_tag(Array)
#2 /<WEBROOT>/httpdocs/wp-includes/shortcodes.php(218): preg_replace_callback('/\\[(\\[?)(su_car...', 'do_shortcode_ta...', '<div class="" s...')
#3 /<WEBROOT>/httpdocs/wp-includes/class-wp-hook.php(287): do_shortcode('<div class="" s...')
#4 /<WEBROOT>/httpdocs/wp-includes/plugin.php(206): WP_Hook->apply_filters('<div class="" s...', Array)
#5 /<WEBROOT>/httpdocs/wp-content/plugins/wordpress-seo/admin/links/class-link-watcher.php(140): apply_filters('the_content', '<div class="" s...')
#6 /<WEBROOT> in /<WEBROOT>/httpdocs/wp-content/plugins/shortcodes-ultimate/includes/shortcodes/carousel.php on line 201
```

**System (please complete the following information):**
 - Plugin version 5.8.0
 - WP Version 5.4

**Comment by vanokhin** [comment] 2020-04-06 18:21
Hi @mcguffin,

posts with no thumbnail are filtered [here](https://github.com/vanokhin/shortcodes-ultimate/blob/master/includes/functions-galleries.php#L101-L107). The error is caused by something else.

Try to use the following shortcode and post here the result:

```
[su_carousel source="taxonomy: category/12" link="post" target="blank" width="200" height="100" responsive="no" items="1" centered="no" arrows="no" mousewheel="no" autoplay="50" speed="4000"]
```

**Comment by mcguffin** [comment] 2020-04-07 08:07
Hi @vanokhin 

Must admin, I didn't dig that deep when I posted the issue. 
The thing I found is, that `su_image_resize()`:

https://github.com/vanokhin/shortcodes-ultimate/blob/87b4081dd27885a006d8db32ea1606740b9530b3/includes/shortcodes/carousel.php#L193-L206

... might return a WP_Error instead of an array:
https://github.com/vanokhin/shortcodes-ultimate/blob/87b4081dd27885a006d8db32ea1606740b9530b3/inc/core/tools.php#L17-L19

IMHO there should be a `is_wp_error()` check somewhere...
I'll send a PR on this later.

After doing some more debug logging I found that the `$thumb` var can be `0` sometimes:
https://github.com/vanokhin/shortcodes-ultimate/blob/8e7373710a95d53e241744dac0ade4803e874062/includes/functions-galleries.php#L101-L107

Using `! intval($thumb)`instead of `! is_numeric($thumb)` fixes the crash too.

I just made up a PR (#109) containing fixes for both.

**Comment by vanokhin** [comment] 2020-04-08 11:55
Merged. Thank you very much for your contribution!

**Closed by vanokhin** 2020-04-08 11:55 UTC
